name: Validate Source of Truth CSV

on:
  pull_request:
    branches: [main]  # Or your main branch name

jobs:
  validate_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Or your preferred version

      - name: Install required libraries
        run: |
          python -m pip install --upgrade pip
          pip install pandas pydantic  # Install pandas and pydantic

      - name: Validate CSV contents
        run: |
          set -x  # Echo commands to help debug
          # Execute the Python script
          python validate_csv.py
          exit_code=$?
          echo "Script completed with exit code: $exit_code"
          if [[ $exit_code -eq 0 ]]; then
            echo "Validation Succeeded"
          else
            echo "Validation Failed"
            exit 1
          fi
