name: Validate Source of Truth CSV

on:
  pull_request:
    branches: [main]  # Or your main branch name

jobs:
  validate_csv:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim-buster  # Use a Python 3.9 slim image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install required libraries
        run: |
          pip install pandas pydantic  # Install pandas and pydantic

      - name: Copy validation script
        run: |
          mkdir -p .github/scripts
          cp validate_csv.py .github/scripts/validate_csv.py

      - name: Validate CSV contents
        run: |
          # Execute the Python script
          python .github/scripts/validate_csv.py
          exit_code=$?
          echo "Script completed with exit code: $exit_code"
          if [ $exit_code -eq 0 ]; then
            echo "Validation Succeeded"
          else
            echo "Validation Failed"
            exit 1
          fi
